<?php

return [
    'ratgeber-website-erstellen' => [
        'title' => 'Website erstellen lassen: Ablauf, Kosten & Checkliste | Sartu',
        'description' => 'Website erstellen lassen: Ablauf, Kosten, Dauer, Inhalte, SEO und Checkliste. So planen kleine Unternehmen eine professionelle Firmenwebsite.',
        'h1' => 'Website erstellen lassen:',
        'accent' => 'Ablauf, Kosten und Checkliste.',
        'lead' => 'Dieser Ratgeber zeigt, was vor einer neuen Website wirklich wichtig ist: Ziele, Seitenstruktur, Texte, Design, SEO, Technik, Kosten und der Weg bis zum Onlinegang.',
        'answer' => 'Wenn Sie eine Website erstellen lassen, sollten zuerst Ziel, Zielgruppe, Seitenumfang, Inhalte, SEO, Technik und laufende Wartung geklärt werden. Eine kleine Firmenwebsite kann bei klaren Inhalten oft in 7 bis 14 Werktagen online gehen; größere Projekte brauchen mehr Planung.',
        'story_label' => 'Wenn Sie starten wollen, aber noch nicht wissen womit',
        'story' => 'Viele Unternehmen wissen: Die alte Website reicht nicht mehr. Unklar ist aber, wie viele Seiten nötig sind, welche Inhalte gebraucht werden und woran man ein gutes Angebot erkennt.',
        'toc' => [
            ['id' => 'start', 'label' => 'Womit anfangen?'],
            ['id' => 'umfang', 'label' => 'Seiten & Umfang'],
            ['id' => 'kosten', 'label' => 'Kosten'],
            ['id' => 'ablauf', 'label' => 'Ablauf'],
            ['id' => 'checkliste', 'label' => 'Checkliste'],
        ],
        'sections' => [
            ['id' => 'start', 'h2' => 'Womit sollte man bei einer neuen Website anfangen?', 'html' => '<p>Der beste Start ist nicht das Design, sondern die Frage: <strong>Was soll die Website leisten?</strong> Soll sie Vertrauen aufbauen, mehr Anfragen bringen, regional gefunden werden, Bewerbungen auslösen oder eine alte Website ersetzen?</p><p>Erst wenn dieses Ziel klar ist, lassen sich Seiten, Texte, Funktionen und SEO sinnvoll planen. Für viele kleine Unternehmen reicht am Anfang eine klare Firmenwebsite mit Startseite, Leistungsseiten, Kontakt, Vertrauenselementen und technischer Basis. Wer mehrere Leistungen oder Standorte sichtbar machen will, braucht mehr Struktur.</p>'],
            ['id' => 'umfang', 'h2' => 'Wie viele Seiten braucht eine Firmenwebsite?', 'html' => '<p>Die Seitenanzahl hängt davon ab, wie viele Themen bei Google einzeln gefunden werden sollen. Ein Onepager bündelt alles auf einer Seite. Das funktioniert für ein klares Angebot, stößt aber bei mehreren Leistungen an Grenzen.</p><ul><li><strong>Onepager:</strong> geeignet für ein Angebot, eine Zielgruppe und schnellen Start.</li><li><strong>Kleine Firmenwebsite:</strong> sinnvoll bei mehreren Leistungen, About-Seite, Kontakt und ersten SEO-Zielen.</li><li><strong>Umfangreiche Website:</strong> sinnvoll bei vielen Leistungen, Standorten, Ratgeberinhalten oder starkem Wettbewerb.</li></ul><p>Mehr zur Entscheidung finden Sie im Ratgeber <a href="ratgeber-onepager.php">Onepager oder mehrseitige Website</a>.</p>'],
            ['id' => 'kosten', 'h2' => 'Was kostet es, eine Website erstellen zu lassen?', 'html' => '<p>Eine professionelle Website kostet 2026 je nach Umfang meist vom niedrigen vierstelligen Bereich bis deutlich über 10.000&nbsp;€. Entscheidend sind Seitenanzahl, Design, Texte, SEO, Technik, Datenschutz und laufende Wartung.</p><p>Wichtig ist, nicht nur den Startpreis zu vergleichen. Prüfen Sie, ob Mobil-Optimierung, Kontaktformular, Basis-SEO, SSL, Datenschutz-Setup, Korrekturrunden und Nutzungsrechte enthalten sind. Eine ausführliche Aufschlüsselung gibt es im Ratgeber <a href="ratgeber-website-kosten.php">Was kostet eine Website 2026?</a>.</p>'],
            ['id' => 'ablauf', 'h2' => 'Wie läuft ein Website-Projekt ab?', 'html' => '<p>Ein sauberer Ablauf reduziert Rückfragen und verhindert Nachträge. Typisch sind diese Schritte:</p><ol><li>Ziel und Umfang klären</li><li>Seitenstruktur und Inhalte planen</li><li>Texte, Bilder und Logo sammeln oder erstellen</li><li>Design-Entwurf prüfen</li><li>Website technisch umsetzen</li><li>Feedback und Korrekturen einarbeiten</li><li>SEO, Formulare, Datenschutz und Ladezeit testen</li><li>Domain umstellen und Website veröffentlichen</li></ol><p>Den konkreten Ablauf bei Sartu finden Sie unter <a href="ablauf.php">in 7 Schritten zur fertigen Website</a>.</p>'],
            ['id' => 'checkliste', 'h2' => 'Checkliste: Was sollte vor dem Start geklärt sein?', 'html' => '<ul><li>Welche Leistung soll mehr Anfragen bringen?</li><li>Welche Zielgruppe soll die Website überzeugen?</li><li>Welche Region oder welcher Standort ist wichtig?</li><li>Gibt es eine bestehende Website, die übernommen oder ersetzt wird?</li><li>Welche Seiten werden gebraucht?</li><li>Sind Logo, Farben, Fotos und Texte vorhanden?</li><li>Wer pflegt Inhalte nach dem Onlinegang?</li><li>Welche laufenden Kosten entstehen für Hosting, Wartung und SEO?</li></ul><p>Sie müssen nicht alles fertig vorbereiten. Gute Website-Planung hilft gerade dann, wenn noch vieles unklar ist.</p>'],
        ],
        'faqs' => [
            ['q' => 'Wie lange dauert es, eine Website erstellen zu lassen?', 'a' => 'Eine kleine Website kann bei vollständigen Inhalten oft in 7 bis 14 Werktagen online sein. Größere Firmenwebsites brauchen mehr Zeit für Struktur, Texte, Design, Feedback und Tests.'],
            ['q' => 'Kann ich eine Website ohne Texte erstellen lassen?', 'a' => 'Ja. Häufig reichen Stichpunkte, alte Unterlagen oder eine bestehende Website als Grundlage. Daraus können professionelle, suchmaschinenoptimierte Website-Texte entstehen.'],
            ['q' => 'Was ist wichtiger: Design oder SEO?', 'a' => 'Beides muss zusammenspielen. Gutes Design schafft Vertrauen und Orientierung; SEO sorgt dafür, dass passende Besucher die Website überhaupt finden.'],
            ['q' => 'Brauche ich für meine Website ein CMS?', 'a' => 'Ein CMS lohnt sich, wenn Inhalte regelmäßig selbst gepflegt werden sollen. Wenn die Seite vor allem schnell, sicher und wartungsarm laufen soll, kann eine schlankere Lösung besser sein.'],
        ],
    ],
    'ratgeber-seo-kosten' => [
        'title' => 'SEO Kosten & Dauer: Was Suchmaschinenoptimierung bringt | Sartu',
        'description' => 'SEO Kosten, Dauer und Leistungen einfach erklärt: OnPage-SEO, technisches SEO, Keywords, Google Ads Vergleich und realistische Erwartungen.',
        'h1' => 'SEO Kosten & Dauer:',
        'accent' => 'was wirklich realistisch ist.',
        'lead' => 'Dieser Ratgeber erklärt, was SEO kostet, wie lange Suchmaschinenoptimierung dauert und welche Maßnahmen für kleine Unternehmen wirklich wichtig sind.',
        'answer' => 'SEO kostet je nach Wettbewerb und Umfang meist vom niedrigen dreistelligen Monatsbereich bis deutlich mehr. Erste Verbesserungen sind oft nach Wochen sichtbar, stabile Rankings brauchen aber meist mehrere Monate.',
        'story_label' => 'Wenn Google die Konkurrenz zeigt',
        'story' => 'Viele Unternehmen haben eine gute Leistung, werden aber online kaum gefunden. SEO löst dieses Problem nicht über Nacht, aber es baut langfristig Sichtbarkeit und planbarere Anfragen auf.',
        'toc' => [
            ['id' => 'kosten', 'label' => 'SEO-Kosten'],
            ['id' => 'dauer', 'label' => 'Dauer'],
            ['id' => 'onpage', 'label' => 'OnPage & Technik'],
            ['id' => 'ads', 'label' => 'SEO vs. Ads'],
            ['id' => 'realistisch', 'label' => 'Erwartungen'],
        ],
        'sections' => [
            ['id' => 'kosten', 'h2' => 'Was kostet SEO für eine Website?', 'html' => '<p>SEO-Kosten hängen von Wettbewerb, Website-Zustand, Seitenumfang, Region und Ziel ab. Für kleine Unternehmen ist oft ein klarer Start sinnvoll: technische Grundlagen, Keyword-Struktur, optimierte Leistungsseiten und bei regionalen Betrieben lokales SEO.</p><p>Ein niedriger Monatsbetrag reicht selten für aggressive Wettbewerbe, kann aber für laufende Pflege, Monitoring und kleinere Optimierungen sinnvoll sein. Wichtig ist, dass die Leistungen konkret benannt werden: Welche Seiten werden optimiert? Welche Keywords werden verfolgt? Welche technischen Probleme werden behoben?</p>'],
            ['id' => 'dauer', 'h2' => 'Wie lange dauert SEO, bis Ergebnisse sichtbar werden?', 'html' => '<p>SEO ist kein Schalter. Technische Verbesserungen, bessere Title-Tags oder neue interne Links können schnell messbar sein. Stabile Rankings entstehen aber meistens über Wochen und Monate.</p><ul><li><strong>0 bis 4 Wochen:</strong> Analyse, Technik, Indexierung, grundlegende Korrekturen.</li><li><strong>1 bis 3 Monate:</strong> erste Bewegungen bei weniger umkämpften Begriffen.</li><li><strong>3 bis 12 Monate:</strong> belastbarere Sichtbarkeit, bessere Inhalte, lokale Signale, Autorität.</li></ul>'],
            ['id' => 'onpage', 'h2' => 'Was ist wichtiger: OnPage-SEO oder technisches SEO?', 'html' => '<p>Beides gehört zusammen. <strong>OnPage-SEO</strong> betrifft Inhalte, Überschriften, Keywords, interne Links und Seitenstruktur. <strong>Technisches SEO</strong> sorgt dafür, dass Google die Website schnell laden, crawlen, verstehen und indexieren kann.</p><p>Eine starke SEO-Seite beantwortet eine konkrete Suchintention vollständig. Sie braucht klare Sprache, gute Struktur, schnelle Ladezeit und interne Links zu verwandten Themen.</p>'],
            ['id' => 'ads', 'h2' => 'SEO oder Google Ads: Was ist besser?', 'html' => '<p>Google Ads bringt sofort bezahlte Klicks, endet aber, sobald kein Budget mehr läuft. SEO dauert länger, baut dafür langfristige Sichtbarkeit auf. Für viele Unternehmen ist die Kombination sinnvoll: Ads für schnelle Nachfrage, SEO für nachhaltige Unabhängigkeit.</p><p>Wer ein knappes Budget hat, sollte zuerst die Website-Basis sauber machen: Seitenstruktur, Ladezeit, Texte und lokale Sichtbarkeit. Werbung auf eine schwache Website verbrennt sonst unnötig Budget.</p>'],
            ['id' => 'realistisch', 'h2' => 'Welche SEO-Versprechen sind unseriös?', 'html' => '<p>Niemand kann Platz 1 bei Google seriös garantieren. Rankings hängen von Wettbewerb, Suchintention, Standort, Website-Qualität, Backlinks, Nutzerverhalten und Google-Updates ab.</p><p>Seriös ist ein SEO-Angebot, wenn es konkrete Maßnahmen, realistische Zeiträume, nachvollziehbare Berichte und verständliche Prioritäten nennt.</p><p>Mehr zur laufenden Betreuung finden Sie auf <a href="leistung-seo.php">SEO-Betreuung</a>.</p>'],
        ],
        'faqs' => [
            ['q' => 'Was kostet SEO pro Monat?', 'a' => 'Für kleine Unternehmen starten sinnvolle SEO-Maßnahmen oft im niedrigen dreistelligen Monatsbereich. Stärkere Wettbewerbe, viele Seiten oder laufende Inhalte benötigen mehr Budget.'],
            ['q' => 'Kann man SEO einmalig machen?', 'a' => 'Eine einmalige SEO-Grundlage ist sinnvoll, ersetzt aber keine laufende Optimierung, wenn Wettbewerb, Inhalte und lokale Sichtbarkeit wachsen sollen.'],
            ['q' => 'Wie findet man die richtigen Keywords?', 'a' => 'Gute Keywords entstehen aus Kundenfragen, Leistungen, Region, Wettbewerb und Kaufabsicht. Entscheidend ist nicht nur Suchvolumen, sondern passende Suchintention.'],
            ['q' => 'Ist SEO für kleine Unternehmen wichtig?', 'a' => 'Ja, wenn neue Kunden über Google suchen. Besonders lokale Dienstleister profitieren von klaren Leistungsseiten, Google-Unternehmensprofil und regionalen Signalen.'],
        ],
    ],
    'ratgeber-lokales-seo' => [
        'title' => 'Lokales SEO: bei Google Maps und „in der Nähe“ gefunden werden | Sartu',
        'description' => 'Lokales SEO einfach erklärt: Google Maps, Google-Unternehmensprofil, Bewertungen, NAP-Daten, lokale Keywords und Sichtbarkeit in der Nähe.',
        'h1' => 'Lokales SEO:',
        'accent' => 'bei Google Maps gefunden werden.',
        'lead' => 'Dieser Ratgeber erklärt, wie regionale Unternehmen in Google Maps, bei „in der Nähe“-Suchen und für lokale Leistungen sichtbarer werden.',
        'answer' => 'Lokales SEO verbessert die Sichtbarkeit für Suchanfragen mit Ortsbezug. Wichtig sind ein gepflegtes Google-Unternehmensprofil, konsistente Kontaktdaten, Bewertungen, lokale Inhalte und passende Leistungsseiten.',
        'story_label' => 'Wenn Kunden in Ihrer Nähe suchen',
        'story' => 'Viele Kaufentscheidungen starten direkt in Google Maps oder mit Suchanfragen wie „in der Nähe“. Wer dort nicht sichtbar ist, verliert Anfragen an Wettbewerber, obwohl die Leistung passen würde.',
        'toc' => [
            ['id' => 'maps', 'label' => 'Google Maps'],
            ['id' => 'profil', 'label' => 'Unternehmensprofil'],
            ['id' => 'bewertungen', 'label' => 'Bewertungen'],
            ['id' => 'website', 'label' => 'Website-Signale'],
            ['id' => 'branchen', 'label' => 'Branchen'],
        ],
        'sections' => [
            ['id' => 'maps', 'h2' => 'Wie wird man bei Google Maps gefunden?', 'html' => '<p>Google Maps bewertet vor allem Relevanz, Entfernung und Bekanntheit. Deshalb muss klar sein, welche Leistungen angeboten werden, wo das Unternehmen aktiv ist und ob andere Nutzer dem Unternehmen vertrauen.</p><p>Ein vollständiges Profil allein reicht selten. Website, Google-Unternehmensprofil, Bewertungen, Fotos, Kategorien und lokale Inhalte sollten zusammenpassen.</p>'],
            ['id' => 'profil', 'h2' => 'Was gehört in ein gutes Google-Unternehmensprofil?', 'html' => '<ul><li>richtiger Firmenname, Adresse, Telefonnummer und Website</li><li>passende Haupt- und Nebenkategorien</li><li>Öffnungszeiten und Sonderöffnungszeiten</li><li>Leistungsbeschreibung mit lokalen Begriffen</li><li>aktuelle Fotos und Beiträge</li><li>Antworten auf Bewertungen und häufige Fragen</li></ul><p>Wichtig ist Konsistenz: Name, Adresse und Telefonnummer sollten überall gleich geschrieben sein.</p>'],
            ['id' => 'bewertungen', 'h2' => 'Wie wichtig sind Bewertungen für lokales SEO?', 'html' => '<p>Bewertungen beeinflussen Vertrauen und Klickrate deutlich. Auch Google wertet Anzahl, Aktualität, Qualität und Reaktionen als Signale. Wichtig ist ein natürlicher, kontinuierlicher Bewertungsaufbau.</p><p>Antworten Sie professionell auf gute und kritische Bewertungen. Das zeigt potenziellen Kunden, dass Sie erreichbar sind und Feedback ernst nehmen.</p>'],
            ['id' => 'website', 'h2' => 'Welche Rolle spielt die Website beim lokalen SEO?', 'html' => '<p>Die Website stützt das Google-Profil. Sie sollte Leistungsseiten mit Ortsbezug, klare Kontaktdaten, strukturierte Daten, schnelle Ladezeiten und mobile Nutzerführung enthalten.</p><p>Für Handwerker, Praxen, Kanzleien und Dienstleister sind lokale Leistungsseiten oft stärker als eine einzige allgemeine Seite. Beispiel: „Badsanierung in Köln“ braucht andere Inhalte als „Heizungswartung in Köln“.</p>'],
            ['id' => 'branchen', 'h2' => 'Für welche Branchen lohnt sich lokales SEO?', 'html' => '<p>Lokales SEO lohnt sich für alle, die Kunden in einem bestimmten Gebiet gewinnen wollen: Handwerker, Praxen, Kanzleien, Restaurants, regionale Händler, Immobilienanbieter, Coaches, Studios, Pflegebetriebe und viele Dienstleister.</p><p>Mehr zur Umsetzung finden Sie auf <a href="leistung-lokales-seo.php">Lokales SEO &amp; Google-Profil</a>.</p>'],
        ],
        'faqs' => [
            ['q' => 'Was bedeutet „in der Nähe“ bei Google?', 'a' => 'Google nutzt Standortsignale, Entfernung, Relevanz und Bekanntheit, um lokale Treffer für Suchanfragen wie „in der Nähe“ zu sortieren.'],
            ['q' => 'Brauche ich eine Adresse für lokales SEO?', 'a' => 'Eine Adresse hilft, ist aber nicht immer zwingend. Dienstleister mit Einzugsgebiet können ebenfalls lokal sichtbar werden, wenn Profil, Website und Leistungsgebiet sauber gepflegt sind.'],
            ['q' => 'Wie lange dauert lokales SEO?', 'a' => 'Erste Verbesserungen können nach wenigen Wochen sichtbar werden. Stabile lokale Sichtbarkeit braucht je nach Wettbewerb meist mehrere Monate.'],
            ['q' => 'Was ist NAP-Konsistenz?', 'a' => 'NAP steht für Name, Address und Phone. Diese Daten sollten auf Website, Google-Profil und Verzeichnissen einheitlich sein.'],
        ],
    ],
    'ratgeber-relaunch-seo' => [
        'title' => 'Website-Relaunch ohne Rankingverlust: SEO-Checkliste | Sartu',
        'description' => 'Website-Relaunch ohne Google-Ranking zu verlieren: URLs, 301-Weiterleitungen, Inhalte, Technik, Tracking, SEO-Checks und Relaunch-Plan.',
        'h1' => 'Website-Relaunch:',
        'accent' => 'SEO und Rankings schützen.',
        'lead' => 'Dieser Ratgeber erklärt, worauf Sie beim Redesign oder Relaunch einer bestehenden Website achten müssen, damit Besucher, Backlinks und Google-Signale nicht verloren gehen.',
        'answer' => 'Ein Website-Relaunch kann Rankings kurzfristig verändern. Das Risiko sinkt deutlich, wenn alte URLs erfasst, wichtige Inhalte übernommen, 301-Weiterleitungen gesetzt, Technik geprüft und die neue Website nach dem Onlinegang überwacht wird.',
        'story_label' => 'Wenn die alte Website bremst, aber Google nicht verloren gehen darf',
        'story' => 'Viele Unternehmen wollen ein moderneres Design, haben aber Angst vor Rankingverlust. Diese Sorge ist berechtigt, wenn Weiterleitungen, Inhalte und Technik nicht sauber geplant werden.',
        'toc' => [
            ['id' => 'risiko', 'label' => 'Ranking-Risiko'],
            ['id' => 'urls', 'label' => 'URLs & Weiterleitungen'],
            ['id' => 'inhalte', 'label' => 'Inhalte übernehmen'],
            ['id' => 'technik', 'label' => 'Technik testen'],
            ['id' => 'checkliste', 'label' => 'Relaunch-Checkliste'],
        ],
        'sections' => [
            ['id' => 'risiko', 'h2' => 'Warum kann ein Relaunch Google-Rankings verändern?', 'html' => '<p>Google bewertet nicht nur das Aussehen einer Website, sondern Inhalte, URLs, interne Links, Ladezeit, Struktur und Signale von außen. Wenn sich beim Relaunch viele dieser Punkte ändern, muss Google die Website neu einordnen.</p><p>Kurzfristige Schwankungen sind normal. Problematisch wird es, wenn alte URLs verschwinden, wichtige Texte gekürzt werden, Seitentitel fehlen oder die neue Website technisch schlechter erreichbar ist.</p>'],
            ['id' => 'urls', 'h2' => 'Warum sind 301-Weiterleitungen so wichtig?', 'html' => '<p>Jede wichtige alte URL braucht ein klares neues Ziel. Eine 301-Weiterleitung sagt Browsern und Suchmaschinen dauerhaft: Diese Seite ist umgezogen. Ohne Weiterleitung landen Besucher, Backlinks und Google auf einer Fehlerseite.</p><ul><li>alte URLs vor dem Relaunch vollständig erfassen</li><li>jede relevante URL auf die passendste neue Seite mappen</li><li>keine pauschale Weiterleitung aller Seiten auf die Startseite</li><li>Weiterleitungen nach dem Onlinegang testen</li></ul>'],
            ['id' => 'inhalte', 'h2' => 'Sollte man alte Texte und Bilder übernehmen?', 'html' => '<p>Wenn Inhalte bereits Rankings oder Anfragen bringen, sollten sie nicht blind gelöscht werden. Oft ist die beste Lösung: übernehmen, verbessern, verständlicher strukturieren und mit aktuellen Informationen ergänzen.</p><p>Bei Bildern zählen Qualität, Nutzungsrechte, Dateigröße und Alt-Texte. Alte Bilder können bleiben, wenn sie professionell wirken und zur neuen Seite passen.</p>'],
            ['id' => 'technik', 'h2' => 'Welche technischen Punkte müssen vor dem Onlinegang geprüft werden?', 'html' => '<ul><li>Indexierbarkeit und Robots-Einstellungen</li><li>Title-Tags, Meta-Descriptions und Überschriften</li><li>Sitemap und Canonical-Links</li><li>Ladezeit und mobile Darstellung</li><li>Kontaktformulare, Tracking und Cookie-Einstellungen</li><li>SSL, Weiterleitungen und 404-Fehler</li></ul><p>Nach dem Onlinegang sollten die wichtigsten Seiten, Rankings, Formularanfragen und Fehler regelmäßig kontrolliert werden.</p>'],
            ['id' => 'checkliste', 'h2' => 'Relaunch-Checkliste für SEO', 'html' => '<ol><li>Bestehende Website crawlen und wichtige Seiten notieren.</li><li>Rankings, Traffic und Anfragen vor dem Relaunch sichern.</li><li>Neue Seitenstruktur festlegen.</li><li>Alte Inhalte übernehmen oder gezielt verbessern.</li><li>Weiterleitungen planen und testen.</li><li>Neue Website mobil, technisch und rechtlich prüfen.</li><li>Nach dem Onlinegang Fehler, Indexierung und Suchleistung beobachten.</li></ol><p>Wenn Ihre Website bereits existiert, finden Sie die passende Umsetzung unter <a href="leistung-redesign.php">Website-Redesign</a>.</p>'],
        ],
        'faqs' => [
            ['q' => 'Verliert eine Website beim Relaunch immer Rankings?', 'a' => 'Nein. Ein sauber geplanter Relaunch kann Rankings erhalten oder langfristig verbessern. Ohne Weiterleitungen und SEO-Prüfung steigt das Risiko aber deutlich.'],
            ['q' => 'Was ist eine 301-Weiterleitung?', 'a' => 'Eine 301-Weiterleitung ist eine dauerhafte Weiterleitung von einer alten URL auf eine neue passende URL. Sie schützt Besucherwege und SEO-Signale.'],
            ['q' => 'Sollte man beim Relaunch alle Texte neu schreiben?', 'a' => 'Nicht zwingend. Gute bestehende Inhalte sollten übernommen und verbessert werden. Schwache oder veraltete Texte können neu strukturiert werden.'],
            ['q' => 'Wann ist ein Relaunch besser als ein kleines Redesign?', 'a' => 'Ein Relaunch ist sinnvoll, wenn Technik, Struktur, Inhalte und mobile Nutzung grundlegend veraltet sind. Ein kleines Redesign reicht, wenn nur Optik und einzelne Inhalte angepasst werden.'],
        ],
    ],
    'ratgeber-website-wartung' => [
        'title' => 'Website-Wartung: Kosten, Hosting, Backups & Sicherheit | Sartu',
        'description' => 'Website-Wartung einfach erklärt: monatliche Kosten, Hosting, SSL, Backups, Updates, Sicherheit, DSGVO und was nach dem Onlinegang wichtig ist.',
        'h1' => 'Website-Wartung:',
        'accent' => 'Kosten, Hosting und Sicherheit.',
        'lead' => 'Dieser Ratgeber erklärt, warum eine Website nach dem Onlinegang weiter betreut werden muss und welche Leistungen in Wartung und Hosting wirklich wichtig sind.',
        'answer' => 'Website-Wartung umfasst Updates, Hosting, SSL, Backups, Sicherheit, Monitoring und technische Fehlerbehebung. Die Kosten liegen je nach Umfang oft zwischen etwa 30 Euro und mehreren hundert Euro pro Monat.',
        'story_label' => 'Wenn niemand die Technik im Blick hat',
        'story' => 'Eine Website wirkt nach außen wie ein fertiges Produkt. Technisch bleibt sie aber ein laufendes System: Server, Sicherheit, Backups, Formulare und Datenschutz müssen zuverlässig funktionieren.',
        'toc' => [
            ['id' => 'kosten', 'label' => 'Kosten'],
            ['id' => 'leistungen', 'label' => 'Leistungen'],
            ['id' => 'backups', 'label' => 'Backups'],
            ['id' => 'dsgvo', 'label' => 'DSGVO & Hosting'],
            ['id' => 'ausfall', 'label' => 'Notfallplan'],
        ],
        'sections' => [
            ['id' => 'kosten', 'h2' => 'Was kostet Website-Wartung pro Monat?', 'html' => '<p>Die Kosten hängen von Technik, Sicherheitsanforderungen, Support und Änderungsumfang ab. Einfache Wartung kann niedrig starten, umfangreiche Betreuung mit Monitoring, Änderungszeit und schneller Reaktion kostet mehr.</p><p>Wichtig ist der Vergleich der enthaltenen Leistungen: Sind Backups, SSL, Updates, Sicherheitsprüfungen, Support und Wiederherstellung enthalten oder werden sie einzeln berechnet?</p>'],
            ['id' => 'leistungen', 'h2' => 'Was beinhaltet Website-Wartung?', 'html' => '<ul><li>Hosting und Serverbetrieb</li><li>SSL-Zertifikat und HTTPS</li><li>Updates und technische Pflege</li><li>regelmäßige Backups</li><li>Sicherheitsprüfung und Wiederherstellung</li><li>Monitoring von Erreichbarkeit und Fehlern</li><li>kleinere Inhaltsänderungen je nach Paket</li></ul><p>Bei Sartu ist das im <a href="leistung-wartung.php">Rundum-Schutz</a> gebündelt.</p>'],
            ['id' => 'backups', 'h2' => 'Wie oft sollten Backups erstellt werden?', 'html' => '<p>Für Unternehmenswebsites sind tägliche Backups sinnvoll. Noch wichtiger ist, dass Backups extern gespeichert und im Ernstfall schnell wiederhergestellt werden können.</p><p>Ein Backup ist nur dann wertvoll, wenn klar ist, welcher Stand wiederhergestellt wird und wer im Notfall reagiert.</p>'],
            ['id' => 'dsgvo', 'h2' => 'Ist Hosting in Deutschland für DSGVO wichtig?', 'html' => '<p>Hosting in Deutschland oder der EU kann die DSGVO-konforme Verarbeitung vereinfachen. Entscheidend sind außerdem Auftragsverarbeitung, SSL, Datenschutzerklärung, Cookie-/Tracking-Einstellungen und ein sicherer Umgang mit Formularanfragen.</p><p>Wer personenbezogene Daten über Kontaktformulare verarbeitet, sollte Sicherheit und Datenschutz nicht als Nebensache behandeln.</p>'],
            ['id' => 'ausfall', 'h2' => 'Was passiert, wenn eine Website ausfällt oder gehackt wird?', 'html' => '<p>Dann zählt ein klarer Plan: Website prüfen, Sicherheitslücke schließen, sauberes Backup einspielen, Passwörter ändern, Formulare und Daten prüfen und die Seite wieder erreichbar machen.</p><p>Gute Wartung verhindert nicht jedes Problem, verkürzt aber Ausfallzeiten und reduziert das Risiko deutlich.</p>'],
        ],
        'faqs' => [
            ['q' => 'Braucht jede Website Wartung?', 'a' => 'Ja. Jede geschäftliche Website sollte technisch aktuell, sicher, gesichert und erreichbar bleiben. Ohne Wartung steigen Sicherheits- und Ausfallrisiken.'],
            ['q' => 'Kann ich Hosting und Wartung trennen?', 'a' => 'Ja, technisch ist das möglich. Praktisch ist eine gemeinsame Betreuung oft einfacher, weil Server, Updates, Backups und Support zusammenpassen.'],
            ['q' => 'Was ist ein SSL-Zertifikat?', 'a' => 'Ein SSL-Zertifikat verschlüsselt die Verbindung zwischen Website und Besucher. Es ist Standard für Vertrauen, Datenschutz und sichere Formulare.'],
            ['q' => 'Wie schnell sollte eine Website laden?', 'a' => 'Mobil sollte eine Website möglichst in wenigen Sekunden nutzbar sein. Schnelle Ladezeiten verbessern Nutzererlebnis, Anfragen und Suchmaschinenbewertung.'],
        ],
    ],
    'ratgeber-website-texte' => [
        'title' => 'Website-Texte schreiben: SEO, Struktur & Kundenansprache | Sartu',
        'description' => 'Website-Texte schreiben lassen oder selbst schreiben: SEO-Texte, Startseite, Leistungsseiten, Keywords, Tonalität, Länge und klare Kundenansprache.',
        'h1' => 'Website-Texte schreiben:',
        'accent' => 'verständlich, verkaufsstark und SEO-tauglich.',
        'lead' => 'Dieser Ratgeber zeigt, welche Texte eine Website braucht, wie SEO-Texte funktionieren und wie Fachsprache verständlich wird, ohne wichtige Suchbegriffe zu verlieren.',
        'answer' => 'Gute Website-Texte beantworten echte Kundenfragen, erklären Nutzen verständlich, verwenden relevante Keywords natürlich und führen Besucher zur nächsten sinnvollen Handlung.',
        'story_label' => 'Wenn Sie wissen, was Sie tun, aber nicht wie Sie es sagen sollen',
        'story' => 'Viele Unternehmen können ihre Leistung gut erklären, sobald sie mit Kunden sprechen. Auf der Website klingt es dann aber oft zu technisch, zu allgemein oder zu dünn für Google.',
        'toc' => [
            ['id' => 'seo-text', 'label' => 'SEO-Text'],
            ['id' => 'seiten', 'label' => 'Welche Texte?'],
            ['id' => 'keywords', 'label' => 'Keywords'],
            ['id' => 'ton', 'label' => 'Tonfall'],
            ['id' => 'ki', 'label' => 'KI-Texte'],
        ],
        'sections' => [
            ['id' => 'seo-text', 'h2' => 'Was ist ein guter SEO-Text?', 'html' => '<p>Ein guter SEO-Text ist kein Keyword-Teppich. Er beantwortet eine konkrete Suchintention besser als andere Seiten, ist logisch gegliedert und bleibt für Menschen leicht verständlich.</p><p>Wichtig sind klare Überschriften, konkrete Beispiele, natürliche Suchbegriffe, interne Links und Antworten auf typische Einwände. Genau diese Verbindung hilft Suchmaschinen und Besuchern.</p>'],
            ['id' => 'seiten', 'h2' => 'Welche Texte braucht eine Firmenwebsite?', 'html' => '<ul><li><strong>Startseite:</strong> Positionierung, Nutzen, wichtigste Leistungen, Vertrauen und Kontaktweg.</li><li><strong>Leistungsseiten:</strong> Problem, Lösung, Ablauf, Preise oder Preisrahmen, FAQ und Handlungsaufforderung.</li><li><strong>Über-uns-Seite:</strong> Vertrauen, Haltung, Arbeitsweise und Zielgruppe.</li><li><strong>Kontaktseite:</strong> niedrige Hürde, klare Erwartungen und einfache Anfrage.</li><li><strong>Ratgeber:</strong> ausführliche Antworten auf große Suchfragen.</li></ul>'],
            ['id' => 'keywords', 'h2' => 'Wie findet man die richtigen Keywords für Website-Texte?', 'html' => '<p>Starten Sie bei echten Kundenfragen: Was wird gesucht, bevor jemand anfragt? Welche Begriffe nutzt die Zielgruppe? Welche Region ist wichtig? Welche Einwände tauchen immer wieder auf?</p><p>Ein gutes Keyword ist nicht nur oft gesucht, sondern passt zur Leistung und zur Absicht des Suchenden. „Kosten“, „Dauer“, „Vergleich“, „in der Nähe“ und „Checkliste“ sind häufig starke Suchmuster.</p>'],
            ['id' => 'ton', 'h2' => 'Wie viel Fachsprache ist sinnvoll?', 'html' => '<p>Fachsprache ist gut, wenn sie Vertrauen schafft und ein Suchbegriff ist. Sie wird problematisch, wenn Kunden nicht verstehen, was gemeint ist. Die beste Lösung ist: Fachbegriff nennen und direkt verständlich erklären.</p><p>Beispiel: „OnPage-SEO“ kann stehen bleiben, wenn danach klar erklärt wird, dass es um Texte, Überschriften, interne Links und Seitenstruktur geht.</p>'],
            ['id' => 'ki', 'h2' => 'Kann KI Website-Texte schreiben?', 'html' => '<p>KI kann helfen, Themen zu sortieren, Varianten zu formulieren und Entwürfe zu beschleunigen. Gute Website-Texte brauchen trotzdem echte Informationen, Zielgruppenverständnis, fachliche Prüfung und redaktionelle Überarbeitung.</p><p>Wer KI-Texte ungeprüft übernimmt, bekommt oft allgemeine Aussagen. Stark werden Texte erst durch konkrete Leistung, Kundenschmerz, Beispiele, regionale Signale und klare Entscheidungshilfen.</p><p>Mehr zur Umsetzung finden Sie unter <a href="leistung-texte.php">Website-Texte schreiben lassen</a>.</p>'],
        ],
        'faqs' => [
            ['q' => 'Wie lang sollte ein Website-Text sein?', 'a' => 'So lang wie nötig, um Suchintention, Nutzen, Ablauf, Vertrauen und Einwände zu beantworten. Es gibt keine feste Wortzahl, die immer richtig ist.'],
            ['q' => 'Sollte jede Leistung eine eigene Seite haben?', 'a' => 'Ja, wenn die Leistung einzeln bei Google gefunden werden soll. Eine eigene Seite kann gezielter auf Suchintention und Fragen eingehen.'],
            ['q' => 'Muss ich Keywords selbst liefern?', 'a' => 'Nein. Hilfreich sind aber Leistungen, Orte, Zielgruppen und typische Kundenfragen. Daraus lassen sich passende Keywords ableiten.'],
            ['q' => 'Sind kurze Texte besser als lange Texte?', 'a' => 'Kurze Texte sind gut, wenn sie vollständig antworten. Bei erklärungsbedürftigen Leistungen sind längere Seiten oft besser, weil sie mehr Fragen und Einwände klären.'],
        ],
    ],
    'ratgeber-website-angebot' => [
        'title' => 'Website-Angebot prüfen: Kosten, Leistungen & Vergleich | Sartu',
        'description' => 'Website-Angebot prüfen: Seitenumfang, Design, Texte, SEO, Technik, Hosting, Wartung, Rechte, Zusatzkosten und faire Angebotsvergleiche einfach erklärt.',
        'h1' => 'Website-Angebot prüfen:',
        'accent' => 'Kosten, Leistungen und Risiken erkennen.',
        'lead' => 'Dieser Ratgeber zeigt, worauf Unternehmen achten sollten, bevor sie ein Website-Angebot annehmen: Umfang, Preis, laufende Kosten, Nutzungsrechte, SEO, Technik und klare Zuständigkeiten.',
        'answer' => 'Ein gutes Website-Angebot nennt Seitenumfang, Designleistung, Texte, Bilder, SEO-Grundlagen, Technik, Datenschutz, Korrekturrunden, Zeitplan, laufende Kosten, Nutzungsrechte und Zusatzleistungen klar. Schwer vergleichbar wird es, wenn wichtige Punkte fehlen oder nur pauschal beschrieben sind.',
        'story_label' => 'Wenn Angebote gleich aussehen, aber etwas anderes bedeuten',
        'story' => 'Viele Website-Angebote klingen ähnlich: moderne Website, responsive Design, SEO und persönliche Betreuung. Entscheidend ist, was genau enthalten ist, was später extra kostet und ob das Ergebnis zur geplanten Kundengewinnung passt.',
        'toc' => [
            ['id' => 'bestandteile', 'label' => 'Was muss drinstehen?'],
            ['id' => 'kosten', 'label' => 'Kosten & Extras'],
            ['id' => 'rechte', 'label' => 'Rechte & Zugang'],
            ['id' => 'vergleich', 'label' => 'Angebote vergleichen'],
            ['id' => 'checkliste', 'label' => 'Checkliste'],
        ],
        'sections' => [
            ['id' => 'bestandteile', 'h2' => 'Was sollte in einem Website-Angebot stehen?', 'html' => '<p>Ein Website-Angebot sollte nicht nur einen Gesamtpreis nennen. Wichtig ist eine verständliche Beschreibung der Leistung: Welche Seiten werden erstellt? Wer schreibt die Texte? Werden Bilder bearbeitet? Sind Mobil-Optimierung, Kontaktformular, Basis-SEO, Datenschutz-Einbindung, Ladezeit und technische Tests enthalten?</p><p>Je konkreter der Umfang beschrieben ist, desto geringer ist das Risiko für Missverständnisse. Begriffe wie „SEO inklusive“ oder „individuelles Design“ sollten erklärt werden, damit klar ist, welche Arbeit wirklich gemeint ist.</p>'],
            ['id' => 'kosten', 'h2' => 'Welche Kosten werden bei Website-Angeboten oft übersehen?', 'html' => '<p>Neben dem Startpreis gibt es häufig laufende Kosten. Dazu gehören Domain, Hosting, SSL, Wartung, Backups, Sicherheitsupdates, Support, mögliche Lizenzkosten und spätere Inhaltsänderungen.</p><p>Prüfen Sie auch, ob Korrekturrunden, Bildrecherche, Texterstellung, zusätzliche Unterseiten, Tracking, Cookie-Einstellungen oder Weiterleitungen bereits enthalten sind. Ein günstiger Einstiegspreis kann teuer werden, wenn viele notwendige Punkte später einzeln berechnet werden.</p>'],
            ['id' => 'rechte', 'h2' => 'Welche Rechte und Zugänge sollten geklärt sein?', 'html' => '<p>Vor der Zusage sollte klar sein, wem Domain, Inhalte, Bilder, Layout, Quellcode und Zugänge gehören. Wichtig sind außerdem Administrator-Zugänge, Hosting-Vertrag, E-Mail-Einstellungen und die Frage, ob die Website später zu einem anderen Anbieter umziehen kann.</p><p>Bei Bildern, Schriften und Vorlagen zählen Nutzungsrechte. Für echte Unternehmensfotos braucht es eine saubere Freigabe der abgebildeten Personen. Bei KI- oder Stockmaterial sollte transparent sein, wofür es eingesetzt wird.</p>'],
            ['id' => 'vergleich', 'h2' => 'Wie vergleicht man Website-Angebote fair?', 'html' => '<p>Vergleichen Sie nicht nur den Endpreis, sondern die enthaltene Leistung. Zwei Angebote können beide „Website mit SEO“ sagen, aber völlig unterschiedliche Ergebnisse liefern. Hilfreich ist ein Vergleich nach Seitenanzahl, Textumfang, SEO-Tiefe, Technik, Wartung, persönlicher Betreuung und laufenden Kosten.</p><p>Ein gutes Angebot muss nicht das größte sein. Es sollte zum Ziel passen: mehr Anfragen, bessere lokale Sichtbarkeit, moderner Auftritt, klarere Leistungen oder sicherer Betrieb.</p>'],
            ['id' => 'checkliste', 'h2' => 'Checkliste: Website-Angebot vor der Zusage prüfen', 'html' => '<ul><li>Welche Seiten und Funktionen sind enthalten?</li><li>Wer liefert oder erstellt Texte, Bilder und Logo?</li><li>Sind SEO-Grundlagen konkret beschrieben?</li><li>Ist die mobile Ansicht inklusive?</li><li>Gibt es klare Korrekturrunden und einen Zeitplan?</li><li>Welche laufenden Kosten entstehen nach dem Start?</li><li>Wer besitzt Domain, Website und Inhalte?</li><li>Ist Wartung, Backup und Sicherheit geregelt?</li><li>Welche Zusatzkosten können später entstehen?</li><li>Gibt es einen klaren nächsten Schritt bis zum Onlinegang?</li></ul><p>Wenn die Antworten fehlen, sollte vor der Zusage nachgefragt werden. Ein verständliches Angebot ist Teil einer seriösen Website-Planung.</p>'],
        ],
        'faqs' => [
            ['q' => 'Was muss in einem Website-Angebot stehen?', 'a' => 'Ein Website-Angebot sollte Umfang, Seitenanzahl, Design, Texte, SEO, Technik, Datenschutz, Korrekturrunden, Zeitplan, laufende Kosten, Rechte und Zusatzleistungen klar benennen.'],
            ['q' => 'Warum sind Website-Angebote schwer vergleichbar?', 'a' => 'Weil Begriffe wie SEO, Design, Wartung oder Betreuung unterschiedlich ausgelegt werden. Entscheidend ist, welche konkrete Leistung hinter den Begriffen steckt.'],
            ['q' => 'Sollte man das günstigste Website-Angebot nehmen?', 'a' => 'Nicht automatisch. Ein günstiges Angebot passt, wenn der Umfang vollständig ist. Fehlen wichtige Leistungen, können Nachträge oder schwache Ergebnisse teurer werden.'],
            ['q' => 'Welche laufenden Kosten gehören in ein Website-Angebot?', 'a' => 'Typische laufende Kosten sind Domain, Hosting, SSL, Wartung, Backups, Sicherheitsupdates, Support, Lizenzen und optional SEO- oder Inhaltsbetreuung.'],
        ],
    ],
    'ratgeber-website-bilder' => [
        'title' => 'Website-Bilder: Welche Fotos eine Firmenwebsite braucht | Sartu',
        'description' => 'Website-Bilder planen: Fotos für Team, Standort, Leistungen, Vertrauen, SEO, Alt-Texte, Bildrechte, Ladezeit und realistische Website-Wirkung.',
        'h1' => 'Website-Bilder:',
        'accent' => 'welche Fotos eine Firmenwebsite braucht.',
        'lead' => 'Dieser Ratgeber erklärt, welche Bilder auf einer Firmenwebsite Vertrauen schaffen, welche Motive wirklich helfen und worauf Sie bei Bildrechten, SEO, Dateigröße und Platzhaltern achten sollten.',
        'answer' => 'Eine gute Firmenwebsite braucht klare, echte und passende Bilder: Team oder Ansprechpartner, Arbeitsumfeld, Standort, Leistungssituationen, Details aus der Arbeit und bei Bedarf neutrale Platzhalter. Wichtig sind Nutzungsrechte, gute Bildqualität, schnelle Ladezeiten und beschreibende Alt-Texte.',
        'story_label' => 'Wenn die Website professionell wirken soll, aber Fotos fehlen',
        'story' => 'Viele Unternehmen starten ohne perfektes Bildmaterial. Das ist lösbar, solange Platzhalter ehrlich bleiben und später durch echte Fotos ersetzt werden. Schwierig wird es, wenn austauschbare Stockbilder Vertrauen vortäuschen oder Bilder technisch zu groß eingebunden werden.',
        'toc' => [
            ['id' => 'motive', 'label' => 'Welche Motive?'],
            ['id' => 'qualitaet', 'label' => 'Qualität'],
            ['id' => 'seo', 'label' => 'SEO & Ladezeit'],
            ['id' => 'rechte', 'label' => 'Bildrechte'],
            ['id' => 'checkliste', 'label' => 'Checkliste'],
        ],
        'sections' => [
            ['id' => 'motive', 'h2' => 'Welche Bilder braucht eine Firmenwebsite?', 'html' => '<p>Die besten Website-Bilder beantworten stille Besucherfragen: Wer steckt dahinter? Wie sieht die Arbeit aus? Ist das Unternehmen echt? Passt die Leistung zu meinem Problem?</p><ul><li><strong>Team oder Ansprechpartner:</strong> schafft Vertrauen und senkt die Kontakthürde.</li><li><strong>Standort oder Arbeitsplatz:</strong> macht das Unternehmen greifbar.</li><li><strong>Leistungssituationen:</strong> zeigen, wie gearbeitet wird.</li><li><strong>Details und Materialien:</strong> wirken hochwertig und konkret.</li><li><strong>Vorher-nachher oder Ergebnisse:</strong> nur verwenden, wenn sie echt und belegbar sind.</li></ul>'],
            ['id' => 'qualitaet', 'h2' => 'Reichen Smartphone-Fotos oder braucht man einen Fotografen?', 'html' => '<p>Gute Smartphone-Fotos können für den Start reichen, wenn Licht, Bildausschnitt und Schärfe stimmen. Für Hero-Bereiche, Teamfotos und wichtige Vertrauenselemente lohnt sich oft ein professionelles Shooting.</p><p>Entscheidend ist nicht nur die Kamera, sondern die Wirkung: Bilder sollten hell, ruhig, realistisch und zur Marke passend sein. Unnatürliche KI-Optik oder generische Stockfotos können schnell weniger vertrauenswürdig wirken.</p>'],
            ['id' => 'seo', 'h2' => 'Wie werden Website-Bilder für SEO und Ladezeit optimiert?', 'html' => '<p>Bilder sollten komprimiert, richtig zugeschnitten und in modernen Formaten wie WebP bereitgestellt werden. Zu große Dateien verlangsamen die Website und verschlechtern die mobile Erfahrung.</p><p>Für SEO helfen sprechende Dateinamen und Alt-Texte. Ein guter Alt-Text beschreibt sachlich, was zu sehen ist, und nutzt wichtige Begriffe nur dann, wenn sie wirklich passen.</p>'],
            ['id' => 'rechte', 'h2' => 'Worauf muss man bei Bildrechten achten?', 'html' => '<p>Für jedes Bild muss klar sein, ob es auf der Website verwendet werden darf. Das gilt für Fotografenbilder, Stockmaterial, KI-Bilder, Kundenprojekte und Fotos mit Personen.</p><p>Wenn Mitarbeitende, Kunden oder Räume erkennbar sind, sollten Einwilligungen und Nutzungsumfang sauber geklärt werden. Bei Stockbildern zählen Lizenzbedingungen, Bearbeitungsrechte und erlaubte Einsatzbereiche.</p>'],
            ['id' => 'checkliste', 'h2' => 'Checkliste: Bilder für die Website vorbereiten', 'html' => '<ul><li>5 bis 10 gute Bilder für Startseite und wichtige Leistungsseiten sammeln.</li><li>Team, Standort, Arbeitssituationen und Details abdecken.</li><li>Unklare Bildrechte vor Veröffentlichung prüfen.</li><li>Hero-Bilder im Querformat und mit ruhiger Fläche für Text planen.</li><li>Bilddateien komprimieren und sinnvoll benennen.</li><li>Alt-Texte sachlich und hilfreich schreiben.</li><li>Platzhalter klar als Platzhalter behandeln und später ersetzen.</li></ul><p>Wenn noch keine echten Fotos vorhanden sind, kann eine Website trotzdem starten. Wichtig ist, keine künstlichen Referenzen, Bewertungen oder Ergebnisse zu erfinden.</p>'],
        ],
        'faqs' => [
            ['q' => 'Welche Bilder braucht eine Firmenwebsite?', 'a' => 'Sinnvoll sind Bilder von Ansprechpartnern, Team, Standort, Arbeitssituationen, Details der Leistung und echten Ergebnissen, sofern diese rechtlich verwendet werden dürfen.'],
            ['q' => 'Kann man mit Platzhalter-Fotos starten?', 'a' => 'Ja, wenn Platzhalter ehrlich genutzt und später ersetzt werden. Sie sollten professionell wirken, aber keine falschen Referenzen, Kunden oder Ergebnisse vortäuschen.'],
            ['q' => 'Sind KI-Bilder für Websites sinnvoll?', 'a' => 'KI-Bilder können für neutrale Stimmungen oder Platzhalter helfen. Für Vertrauen, Team, Standort und echte Arbeit sind reale Fotos meist stärker.'],
            ['q' => 'Wie wichtig sind Alt-Texte für Bilder?', 'a' => 'Alt-Texte helfen Suchmaschinen und Screenreadern zu verstehen, was auf einem Bild zu sehen ist. Sie sollten kurz, beschreibend und natürlich formuliert sein.'],
        ],
    ],
];
